{% set name = "moviepy" %}
{% set version = "1.0.2" %}
{% set sha256 = "00591a8a5288d323c45a49538dce2cf3ed4211b8cbf63e05c7c2a4c66a175c2a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python
    - decorator >=4.0.2,<5.0
    - imageio >=2.5,<3.0
    - imageio-ffmpeg >=0.2.0
    - tqdm >=4.11.2,<5.0
    - numpy
    - requests >=2.8.1,<3.0
    - proglog <=1.0.0
    - ffmpeg

test:
  imports:
    - moviepy
    - moviepy.audio
    - moviepy.audio.fx
    - moviepy.audio.fx.all
    - moviepy.audio.io
    - moviepy.audio.tools
    - moviepy.video
    - moviepy.video.compositing
    - moviepy.video.fx
    - moviepy.video.fx.all
    - moviepy.video.io
    - moviepy.video.tools

about:
  home: https://zulko.github.io/moviepy
  license: MIT
  license_file: LICENCE.txt
  summary: Video editing with Python

  doc_url: https://zulko.github.io/moviepy
  dev_url: https://github.com/Zulko/moviepy

extra:
  recipe-maintainers:
    - jakirkham
