{% set name = "moviepy" %}
{% set version = "0.2.3.4" %}
{% set sha256 = "d374864f5eaf4acaf0e6ac837620d29c5d9815bd5c2d48dc24066ae9fcc1b0d0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - decorator >=4.0.2,<5.0
    - imageio >=2.1.2,<3.0
    - tqdm >=4.11.2,<5.0
    - numpy
    - ffmpeg

test:
  imports:
    - moviepy
    - moviepy.audio
    - moviepy.audio.fx
    - moviepy.audio.fx.all
    - moviepy.audio.io
    - moviepy.audio.tools
    - moviepy.video
    - moviepy.video.compositing
    - moviepy.video.fx
    - moviepy.video.fx.all
    - moviepy.video.io
    - moviepy.video.tools
    - tests

  requires:
    - coveralls
    - matplotlib ==2.0.0
    - nose
    - pytest >=2.8.0
    - pytest-cov
    - scikit-image ==0.13.0
    - scipy ==0.19.0
    - scikit-learn

about:
  home: https://zulko.github.io/moviepy
  license: MIT
  license_file: LICENCE.txt
  summary: Video editing with Python

  doc_url: https://zulko.github.io/moviepy
  dev_url: https://github.com/Zulko/moviepy

extra:
  recipe-maintainers:
    - jakirkham
